# <span style="color:#54B1FF">Parsing data:</span> &nbsp; <span style="color:#1B3EA9"><b>CSV files</b></span>

<br>

To **parse** means to read and interpret. Parsing a data file means that one reads the file and extracts relevant information from it.

The CSV or commma-separated value format is one of the most common ways of saving data.

While high-level packages like `numpy` and `pandas` are usually sufficient for parsing CSV files, occasionally CSV files have irregularities that require custom programming.

This notebook demonstrates both easy CSV reading using `numpy` and `pandas`, and lower-level reading

<br>

⚠️ **NOTE!**  &nbsp; &nbsp; All data files are saved in the same directory as this notebook.

<br>


___

First let's import the modules we'll need for this lecture.

In [1]:
import csv
import numpy as np
import pandas as pd

<a name="toc"></a>
# Table of Contents

* [pd.read_csv](#pd.read_csv)
    * [Simple CSV](#pd-simple)
    * [Headers](#pd-headers)
    * [Comments](#pd-comments)
* [np.loadtxt](#np.loadtxt)
    * [Simple CSV](#np.loadtxt-simple-csv)
    * [Getting rows & columns](#rows-columns)
    * [Headers](#np.loadtxt-headers)
    * [Comments](#np.loadtxt-comments)
* [csv](#csv)
    * [Simple CSV](#csv-simple-csv)
    * [Headers](#csv-headers)
    * [Comments](#csv-comments)
* [open](#open)
    * [Simple CSV](#open-simple-csv)
    * [Headers](#open-headers)
    * [Comments](#open-comments)
    * [Complex structure](#open-complex)

* [Summary](#summary)

___

<a name="pd.read_csv"></a>
# Using `pd.read_csv` to read text files
[Back to Table of Contents](#toc)
<br>

The [pd.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) function is the easiest way to read well-formatted text data.

___

<a name="pd-simple"></a>
## `pd.read_csv` <span style="background-color:powderblue;">Simple CSV file</span>
[Back to Table of Contents](#toc)
<br>

The `data0.csv` file contains the following values:

| | | |
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The actual text looks like this:

```
1,10.1,10.5
2,9.8,11.8
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
```

Simple data files like this can be read using `pd.read_csv`, along with `header=None` to indicate that there are no header columns in this file.


In [2]:
df = pd.read_csv('data0.csv', header=None)
a  = np.array( df )

print( df )
print()
print( a )

   0     1     2
0  1  10.1  10.5
1  2   9.8  11.8
2  3  12.1  15.1
3  4  18.5  18.9
4  5  12.8  14.1

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


Note that **pandas** reads the data into a special data object called a **data frame** (i.e., `df`).  Data frames have a variety of advantages. The next section describes one key advantage, when there are header rows.

Note also that **pandas** data frames can be easily converted to **numpy** arrays.

___
<a name="pd-headers"></a>
## `pd.read_csv` <span style="background-color:powderblue;">CSV file with header rows</span>
[Back to Table of Contents](#toc)

<br>

The `data1.csv` file contains the following:

|PersonID|Before|After|
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The actual text looks like this:

```
PersonID,Before,After
1,10.1,10.5
2,9.8,11.8
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
```

This file has one header row containing column labels. **pandas** deals with this type of data automatically:

In [3]:
df = pd.read_csv('data1.csv')
a  = np.array( df )

print( df )
print()
print( a )

   PersonID  Before  After
0         1    10.1   10.5
1         2     9.8   11.8
2         3    12.1   15.1
3         4    18.5   18.9
4         5    12.8   14.1

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


Note that the data frame is printed along with the column headers. This can make it quite convenient to understand the meanings of individual columns. Note also that individual columns can be accessed using their names, like this:

In [4]:
c0 = df['Before']

print(c0)
print()
print( np.array(c0) )

0    10.1
1     9.8
2    12.1
3    18.5
4    12.8
Name: Before, dtype: float64

[10.1  9.8 12.1 18.5 12.8]


___
<a name="pd-comments"></a>
## `pd.read_csv` <span style="background-color:powderblue;">CSV file with comments</span>
[Back to Table of Contents](#toc)
<br>

The `data2.csv` file contains the following text:


<br>


```
%% This is a header comment. Skip it using " skiprows=2 ".
PersonID,Before,After
1,10.1,10.5
2,9.8,11.8
%% This is a general comment. Skip it using " comments='%%' "
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
%% This is a footer comment. Skip it using " comments='%%' "
```

<br>


⚠️ When comments exist in CSV files, it is usually difficult to display the file contents in a simple table, so only a text display is shown above.

Comments can be ignored with the `comment` keyword, like this:

In [5]:
df = pd.read_csv('data2.csv', comment='%')

print(df)

   PersonID  Before  After
0         1    10.1   10.5
1         2     9.8   11.8
2         3    12.1   15.1
3         4    18.5   18.9
4         5    12.8   14.1


___

<a name="np.loadtxt"></a>
# Using `np.loadtxt` to read text files
[Back to Table of Contents](#toc)
<br>

The [np.loadtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) function is the second-easiest way to read well-formatted text data.

___

<a name="np.loadtxt-simple-csv"></a>
## `np.loadtxt` <span style="background-color:powderblue;">Simple CSV file</span>
[Back to Table of Contents](#toc)
<br>

The `data0.csv` file contains the following values:

| | | |
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The actual text looks like this:

```
1,10.1,10.5
2,9.8,11.8
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
```

Simple data files like this can be read using `np.loadtxt`, along with `delimiter=','` to indicate that values are separated by comma characters.


In [6]:
a = np.loadtxt('data0.csv', delimiter=',')
print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


<a name="rows-columns"></a>
## <span style="background-color:powderblue;">Getting rows / columns from imported data:</span>
[Back to Table of Contents](#toc)
<br>

In [7]:
row0 = a[0,:]   # first row, same as "row0 = A[0]"
row1 = a[1,:]   # second row, same as "row1 = A[1]"

col2 = a[:,2]   # third column

print('First row: ', row0)
print('Second row: ', row1)
print('Third column: ', col2)

First row:  [ 1.  10.1 10.5]
Second row:  [ 2.   9.8 11.8]
Third column:  [10.5 11.8 15.1 18.9 14.1]


___
<a name="np.loadtxt-headers"></a>
## `np.loadtxt` <span style="background-color:powderblue;">CSV file with header rows</span>
[Back to Table of Contents](#toc)

<br>

The `data1.csv` file contains the following:

|PersonID|Before|After|
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The actual text looks like this:

```
PersonID,Before,After
1,10.1,10.5
2,9.8,11.8
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
```

This file has one header row containing column labels. When header rows like this are present, use the `skiprows` keyword argument to skip these lines:

In [8]:
a = np.loadtxt('data1.csv', delimiter=',', skiprows=1)
print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="np.loadtxt-comments"></a>
## `np.loadtxt` <span style="background-color:powderblue;">CSV file with comments</span>
[Back to Table of Contents](#toc)
<br>

The `data2.csv` file contains the following text:


<br>


```
%% This is a header comment. Skip it using " skiprows=2 ".
PersonID,Before,After
1,10.1,10.5
2,9.8,11.8
%% This is a general comment. Skip it using " comments='%%' "
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
%% This is a footer comment. Skip it using " comments='%%' "
```

<br>


⚠️ When comments exist in CSV files, it is usually difficult to display the file contents in a simple table, so only a text display is shown above.

Comments can be ignored with the `comments` keyword, like this:

In [9]:
a = np.loadtxt('data2.csv', delimiter=',', skiprows=2, comments='%%')
print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="csv"></a>
# csv
[Back to Table of Contents](#toc)
<br>

Python's native [csv](https://docs.python.org/2/library/csv.html) package offers a more comprehensive, albeit more complex, way to deal with CSV files.

___
<a name="csv-simple-csv"></a>
## `csv` <span style="background-color:powderblue;">Simple CSV</span>
[Back to Table of Contents](#toc)
<br>


Let's reconsider the `data0.csv` file:

||||
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The `csv` package can be used to read these data as follows.

In [10]:

with open('data0.csv', 'r') as csvfile:             # open the file ("with" automatically closes the file)
    reader = csv.reader(csvfile, delimiter=',')  # a CSV reader objects
    rows   = [row for row in reader]             # all text rows
    a      = np.array( rows, dtype=float )       # convert rows of text to an array of float numbers

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="csv-headers"></a>
## `csv` <span style="background-color:powderblue;">CSV with header rows</span>
[Back to Table of Contents](#toc)
<br>


Let's reconsider the `data1.csv` file:

|PersonID|Before|After|
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

The headers can be ignored by skipping the first row. 

In [11]:
with open('data1.csv', 'r') as csvfile:             # open the file ("with" automatically closes the file)
    reader = csv.reader(csvfile, delimiter=',')  # a CSV reader objects
    rows   = [row for row in reader]             # all text rows
    a      = np.array( rows[1:], dtype=float )   # ignore first row

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="csv-comments"></a>
## `csv` <span style="background-color:powderblue;">CSV with comments</span>
[Back to Table of Contents](#toc)
<br>


The `data2.csv` file contains the following text:


<br>


```
%% This is a header comment. Skip it using " skiprows=2 ".
PersonID,Before,After
1,10.1,10.5
2,9.8,11.8
%% This is a general comment. Skip it using " comments='%%' "
3,12.1,15.1
4,18.5,18.9
5,12.8,14.1
%% This is a footer comment. Skip it using " comments='%%' "
```

<br>


Comments can be ignored using the `startswith` function on the first row entry like this:

In [12]:
with open('data2.csv', 'r') as csvfile:             # open the file ("with" automatically closes the file)
    reader = csv.reader(csvfile, delimiter=',')  # a CSV reader objects
    rows   = []
    for row in reader:
        if not row[0].startswith('%%'):
            rows.append(row)
    a      = np.array( rows[1:], dtype=float )   # ignore first row

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="open"></a>
# open
[Back to Table of Contents](#toc)
<br>

The `open` command provides the most flexible way to read data from text files.

The `open` command was used above to create a file object `csvfile`, and then `csvfile` was read using `csv.reader`. However, `csv.reader` is not necessary. Instead the data can be read as strings as shown below.

___
<a name="open-simple-csv"></a>
## `open` <span style="background-color:powderblue;">Simple CSV</span>
[Back to Table of Contents](#toc)
<br>

The easiest way to read data is to read all of the lines at once, then parse the lines afterwards, as shown below.

⚠️  This is usually only possible when the data file is not very large (e.g. less than 2 MB).

<br>

`data0.csv` contents:

||||
|-----|-----|-----|
|1|10.1|10.5|
|2|9.8|11.8|
|3|12.1|15.1|
|4|18.5|18.9|
|5|12.8|14.1|

In [13]:
with open('data0.csv', 'r') as fid:             # open the file ("with" automatically closes the file)
    lines  = fid.readlines()

print(lines)


['1,10.1,10.5\n', '2,9.8,11.8\n', '3,12.1,15.1\n', '4,18.5,18.9\n', '5,12.8,14.1']


Each line can be parsed using the `strip` and `split` functions like this:

In [14]:
s = lines[0]
print( s.strip() )     # removes unneeded characters like "newline" (/n)
print( s.split(',') )  # separates the values into a list

1,10.1,10.5
['1', '10.1', '10.5\n']


Thus a single line can be parsed as follows:

In [15]:
print( s.strip().split(',') )

['1', '10.1', '10.5']


And this parsed line can be converted to an array as follows:

In [16]:
a = np.array( s.strip().split(','), dtype=float )
print(a)

[ 1.  10.1 10.5]


Putting it all together:

In [17]:
with open('data0.csv', 'r') as fid:
    lines  = fid.readlines()
    rows   = [line.strip().split(',') for line in lines]
    a      = np.array(rows, dtype=float)

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="open-headers"></a>
## `open` <span style="background-color:powderblue;">Headers</span>
[Back to Table of Contents](#toc)
<br>

When there are `n` header rows, skip them using `lines[n:]` as follows:

In [18]:
with open('data1.csv', 'r') as fid:
    lines  = fid.readlines()
    rows   = [line.strip().split(',') for line in lines[1:]]  # skip the first row
    a      = np.array(rows, dtype=float)

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="open-comments"></a>
## `open` <span style="background-color:powderblue;">Comments</span>
[Back to Table of Contents](#toc)
<br>

When there are comments, use `startwith` to ignore unneeded lines.

In [19]:
with open('data2.csv', 'r') as fid:
    lines   = fid.readlines()
    rows    = []
    for line in lines[2:]:    # skip the first two rows
        if line.startswith('%%'):
            continue
        row = line.strip().split(',')
        rows.append( row )
    a      = np.array(rows, dtype=float)

print(a)

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


Once you have a working function like this, it may be useful to create your own custom loading function, like this:

In [20]:

def myload(fname, skiprows=0, comments=None):
    with open(fname, 'r') as fid:
        lines   = fid.readlines()
    rows    = []
    for line in lines[skiprows:]:
        if comments is not None:
            if line.startswith(comments):
                continue
        row = line.strip().split(',')
        rows.append( row )
    a      = np.array(rows, dtype=float)
    return a



a0        = myload('data0.csv')
a1        = myload('data1.csv', skiprows=1)
a2        = myload('data2.csv', skiprows=2, comments='%%')


print(a0)
print()
print(a1)
print()
print(a2)



[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]

[[ 1.  10.1 10.5]
 [ 2.   9.8 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="open-complex"></a>
## `open` <span style="background-color:powderblue;">Complex text file</span>
[Back to Table of Contents](#toc)
<br>

Occasionally data files can be very poorly formatted, making it difficult to use `np.loadtxt` and `csv.reader`.  For such cases, `open` is usually the only option.

Here is an example of a poorly formatted text file (`data3.csv`):

```
% First line

PersonID,Before,After
1,10.1,,10.5

2,,11.8

3,12.1,15.1
4,18.5,18.9
5,12.8,14.1




# Last line
```

<br>

**Notes**:

* There are a variety of empty lines
* The first data row contains too many commas
* The second data row contains an empty value
* Different comment symbols are used on the first (`%`) and last (`#`) lines

<br>

In these cases, it is usually only possible to create a custom reader.

Here is one way to read the data in `data3.csv`:

In [21]:
with open('data3.csv', 'r') as fid:
    lines   = fid.readlines()

rows    = []
for line in lines[3:]:
    if line.startswith('%') or line.startswith('#'):
        continue
    row = line.strip().split(',')
    if len(row) < 3:   # row has fewer than 3 columns
        continue
    if len(row) > 3:   # row has more than 3 columns
        row.pop( row.index('') )   # remove the empty entry
    rows.append( row )

a        = np.array(rows, dtype=str)  # string array
a[a==''] = 'nan'   # set empty entries to "nan"  (not a number)
a        = np.array(a, dtype=float)

print(a)

[[ 1.  10.1 10.5]
 [ 2.   nan 11.8]
 [ 3.  12.1 15.1]
 [ 4.  18.5 18.9]
 [ 5.  12.8 14.1]]


___
<a name="summary"></a>
# Summary
[Back to Table of Contents](#toc)

* This notebook has demonstrated how to **parse** (i.e., read and interpret) a variety of relatively simple CSV files.

* Real-world data are stored in a variety of text formats. CSV is one of the most common formats.

* As a data scientist, you must be able to deal with a variety of file formats, as well as problems within specific files.

* Useful Python functions for reading CSV files are listed below, in the general order in which they should be applied. If the data are formatted well, then `pd.read_csv` and / or `np.loadtxt` should be sufficient. With data formatting imperfections you may need to use `csv.reader` or even `open` to comprehensively deal with those problems.

    * `pd.read_csv`
    * `np.loadtxt`
    * `csv.reader`
    * `open`
