# Assigning array rows / columns to variables

Array rows and columns can be assigned to variable names like this:

In [1]:
import numpy as np

np.random.seed(0)
a         = np.random.randn(5, 2)   # 5 x 2 array of random numbers
b,c       = a.T  # each column assigned to a different variable
d,e,f,g,h = a    # each row assinged to a different variable


___

## Explanation:

Consider the following code:

In [2]:
a = np.random.randn(5, 2)   # 5 x 2 array of random numbers
b = a[0,:]   # the 1st row of a
b = a[0]     # also the 1st row of a
c = a[1]     # the 2nd row of a

print( a )
print()
print(b)
print()
print(c)

[[ 0.14404357  1.45427351]
 [ 0.76103773  0.12167502]
 [ 0.44386323  0.33367433]
 [ 1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574]]

[0.14404357 1.45427351]

[0.76103773 0.12167502]


<br>

Now consider the transpose of "a":

In [3]:
aa = a.T     # 2 x 5 array (transpose of a)
b  = aa[0]   # the 1st row of aa, equivalent to the 1st column of a
c  = aa[1]   # the 2nd row of aa, equivalent to the 2nd column of a

print( aa )
print()
print( b )
print()
print( c )

[[ 0.14404357  0.76103773  0.44386323  1.49407907  0.3130677 ]
 [ 1.45427351  0.12167502  0.33367433 -0.20515826 -0.85409574]]

[0.14404357 0.76103773 0.44386323 1.49407907 0.3130677 ]

[ 1.45427351  0.12167502  0.33367433 -0.20515826 -0.85409574]


<br>

Now consider assigning values to multiple variable in a single line:

In [4]:
b,c = 10, 20        # assign values of 10 and 20 to variables b and c, respectively
b,c = aa[0], aa[1]  # assign rows of aa to variables b and c
b,c = aa            # (same as above) assign rows of aa to variables b and c

<br>

Now put everything together, to assign the columns of a to variables `b` and `c`:

In [5]:
a   = np.random.randn(5, 2)   # 5 x 2 array of random numbers
b,c = a.T                     # assign columns of aa to variables b and c

print(a)
print()
print(b)
print()
print(c)

[[-2.55298982  0.6536186 ]
 [ 0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567]
 [ 0.04575852 -0.18718385]
 [ 1.53277921  1.46935877]]

[-2.55298982  0.8644362   2.26975462  0.04575852  1.53277921]

[ 0.6536186  -0.74216502 -1.45436567 -0.18718385  1.46935877]
