# <span style="color:#54B1FF">Python:</span> &nbsp; <span style="color:#1B3EA9"><b>Generating random data</b></span>

<br>


___

## Gaussian random values

[Gaussian distributions](https://en.wikipedia.org/wiki/Normal_distribution), or equivalently: normal distributions, are characterized by parameters $\mu$ and $\sigma$, which represent the distribution's mean and standard deviation, respectively.

The standard normal distribution has parameters: $\mu=0$ and $\sigma=1$. For this distribution, nearly all values are expected to lie between -3 and +3.

Random values from the standard normal distribution can be generated using either the **random** or **numpy** packages like this: 

In [1]:
import random
import numpy as np

mu    = 0   # mean
sigma = 1   # standard deviation

x0    = random.gauss(mu, sigma)
x1    = np.random.randn()

print( x0 )
print( x1 )

0.5522659103126828
-0.36396823947485324


Here `randn` means "random normal".

Random values from other Gaussian distributions (other than the standard normal distribution) can be generated by changing `mu` and `sigma` like this:

In [2]:
mu    = 100
sigma = 10

x0    = random.gauss(mu, sigma)
x1    = mu + sigma * np.random.randn()

print( x0 )
print( x1 )

94.85508439824594
104.4863294578825


Note that `np.random.randn` does not accept `mu` or `sigma` as input arguments. Instead you must first scale the distribution using `sigma`, then add `mu`, as demonstrated in the Python cell above.

___

## Uniform random values

The [uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_(continuous)) is characterized by parameters $a$ and $b$, where all values between $a$ and $b$ have an equal probability of occurring.

The standard uniform distribution has parameters $a=0$ and $b=1$.

Random values from the standard uniform distibution can be generated using the `random.uniform` or `np.random.rand` functions, like this:

In [3]:
a  = 0
b  = 1

x0 = random.uniform(a, b)
x1 = np.random.rand()

print(x0, x1)

0.5755189370586425 0.17472819552526164


Values from other uniform distributions can be generated by changing `a` and `b`, and shifting the standard normal distribution, like this:

In [4]:
a = 10
b = 20

x0 = random.uniform(a, b)
x1 = a + (b-a) * random.uniform(0, 1)
x2 = a + (b-a) * np.random.rand()

print(x0)
print(x1)
print(x2)


16.997422155424616
16.600565145900006
11.341314940397492


___

## Controlling / reproducing random numbers 

When you execute the commands above, your computer might generate different random numbers than the ones listed above. If this occurs, it means that the [random number generator](https://en.wikipedia.org/wiki/Random_number_generation) (RNG) in your computer has a different state than the RNG state in the computer on which this notebook was created.

Additionally, if you run these commands multiple times, you will see that the RNG produces different values each time:

In [5]:
x0    = random.gauss(mu, sigma)
x1    = random.gauss(mu, sigma)
x2    = random.gauss(mu, sigma)

print(x0, x1, x2)

98.73990300840568 82.17530359965761 107.72470724981733


To control RNG values, both on your computer and across computers, you need to set the RNG state. This can be done using the `seed` command like this:

In [6]:
random.seed(0)
x0 = random.gauss(mu, sigma)
print(x0)

x1 = random.gauss(mu, sigma)
print(x1)

random.seed(0)
x2 = random.gauss(mu, sigma)
print(x2)

109.41715404680664
86.0342189529885
109.41715404680664


Note that `x0` and `x1` have different values because the RNG seed was not set immediately before generating the `x1` value. Note that calling any RNG function (like `random.gauss`) will change the RNG state, and thus produce a new value.

In contrast, the `x0` and `x2` values are identical, because the RNG state was controlled using the `seed` function.

The seed function accepts any integer:

In [7]:
random.seed(101)
print( random.gauss(mu, sigma) )

random.seed(12345)
print( random.gauss(mu, sigma) )

random.seed(101)
print( random.gauss(mu, sigma) )

94.25532826939774
98.76199204411147
94.25532826939774


The same type of RNG control can be applied to RNG in NumPy using the `np.random.seed` function:

In [9]:
np.random.seed(0)
x = np.random.randn()
print(x)

x = np.random.randn()
print(x)

np.random.seed(0)
x = np.random.randn()
print(x)

1.764052345967664
0.4001572083672233
1.764052345967664


___

## Generating many random numbers

The `random` package is very convenient for generating single random values, but `numpy` is much more convenient for  generating multiple random values.  To generate multiple values, one simply needs to add the desired array dimensions as parameters to `np.random` functions, like this:

In [11]:
a = np.random.randn(2, 3)
print( a )

[[-0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773]]


Note that a 2 x 3 array of random values has been generated.

Additionally, note that RNG seeding also works for arrays:

In [12]:
np.random.seed(0)
a = np.random.randn(2,3)
print(a)
print()


a = np.random.randn(2,3)
print(a)
print()


np.random.seed(0)
a = np.random.randn(2,3)
print(a)
print()

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]

[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]

