# <span style="color:#54B1FF">Python:</span> &nbsp; <span style="color:#1B3EA9">**Arrays**</span>

<br>



<a name="toc"></a>
# Table of Contents

* [Creating arrays](#creating)
* [Math with arrays](#math)
* [Differences between arrays and lists](#differences)


___

<a name="creating"></a>
# Creating arrays
[Back to Table of Contents](#toc)
<br>

Although many types of arrays exist in Python, we will only consider NumPy arrays here.

Arrays can be created as follows:

In [1]:
import numpy as np

a = np.array( [1, 3, 5] )

print( a )
print( type(a) )


[1 3 5]
<class 'numpy.ndarray'>


<br>

Notes:
* [NumPy](https://numpy.org) is a Python package, and means "Numerical Python"
* We will discuss more about packages and the `import` command in the next section (the next notebook)
* Creating an array is almost the same as creating a list. The only difference is that the function `np.array` converts the list into an array.
* The data type is `numpy.ndarray`;  `ndarray` means "n-dimensional array"

The example above shows creation of a one-dimensional array. A two-dimensional array can be created using a list of lists, like this:

In [2]:
b = np.array( [ [1,2,3] , [4,5,6] ] )

print( b )

[[1 2 3]
 [4 5 6]]


Note that this array has two rows and three columns. We can see this more clearly using the `shape` property of the array:

In [3]:
print( b.shape )

(2, 3)


Contrast this with `a`'s `shape` value:

In [4]:
print( a.shape )

(3,)


Note that `shape` has two values for `b`, and one value for `a`. This means that `b` is a 2D array, and that `a` is a 1D array. We can see this more explicitly using the `ndim` property, where `ndim` means "number of dimensions":

In [5]:
print( a.ndim )
print( b.ndim )

1
2


The examples above deal with 1D and 2D arrays, but it is possible to have 3D, 4D and $n$D arrays. This is why the data type is called `ndarray`.

In [6]:
print( type(a) )
print( type(b) )

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


You can think of a 2D array as a spreadsheet like a sheet in Excel, where each (row,column) cell contains a value.

For 1D arrays, individual values can be accessed just like for lists:

In [7]:
print( a[0] )
print( a[1] )
print( a[2] )

1
3
5


For 2D arrays, you must specify two values to index cells:

In [8]:
print( b[0,0] )
print( b[0,1] )
print( b[0,2] )
print( b[1,0] )
print( b[1,1] )
print( b[1,2] )

1
2
3
4
5
6


For 1D arrays, you can access a range of elements using the `:` operator, like this:

In [9]:
print( a[0:2] )

[1 3]


You can also access multiple elements using a list of indices, like this:

In [10]:
print( a[ [0,2] ] )

[1 5]


Note that this returns the first (index=0) and third (index=2) elements.

For 2D arrays, you can use the `:` operator to access all elements along the specified dimension. For example, to access all the rows, use `:` as the index for the first dimension:

In [11]:
print( b[:,1:3] )

[[2 3]
 [5 6]]



___

<a name="math"></a>
# Math with arrays
[Back to Table of Contents](#toc)
<br>

A key advantage of arrays is that they can easily be combined with standard mathematical operations.  For example: 

In [12]:
a = np.array( [0, 2, 4] )

print( a + 10 )
print( a * 2 )

[10 12 14]
[0 4 8]


Note that the mathematical operations have been separately applied to each element of the array.

You can easily combine operations:

In [13]:
print( (10 * a) + 1 )

[ 1 21 41]


If using multiple arrays, the mathematical operations are applied element-by-element:

In [14]:
a0 = np.array( [0, 1, 2] )
a1 = np.array( [10, 20, 30] )

print( a0 + a1 )
print( a0 * a1 )

[10 21 32]
[ 0 20 60]


___

<a name="differences"></a>
# Differences between arrays and lists
[Back to Table of Contents](#toc)
<br>

A key difference between lists and arrays is that mathematical operations can not be applied to lists:

In [15]:
a = [1, 2, 3]
print( 2 * a )

[1, 2, 3, 1, 2, 3]


Note that this command has duplicated the list, rather than applying a mathematical operation.

Another advantage of arrays is that many useful calculations are attached to NumPy arrays as "array methods". For example, the minimum and maximum value of an array can be calculated like this:

In [16]:
a = np.array( [10, 20, 30] )

print( a.min() )
print( a.max() )

10
30


The mean (average) and standard deviation values can be calculated like this:

In [17]:
print( a.mean() )
print( a.std() )

20.0
8.16496580927726


Note that these methods do not exist for lists.

For data analysis purposes, working with arrays is almost always easier than working with lists or tuples, so most of this Open Book uses arrays.


___

Since this Open Book extensively uses arrays, please learn to love NumPy arrays!

Search the internet for "numpy tutorial" or "numpy array examples" and you find lots of useful information about arrays and how they can be used. Here are two example tutorials:

* [NumPy Quickstart tutorial](https://numpy.org/devdocs/user/quickstart.html)
* [NumPy 配列の基礎](http://www.kamishima.net/mlmpyja/nbayes1/ndarray.html)